# MoveIt uses this configuration for controller management
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  # the controller manager runs in the /lwr namespace
  controller_names:
    - lwr/joint_trajectory_controller

  lwr/joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - lwr_a1_joint
      - lwr_a2_joint
      - lwr_e1_joint
      - lwr_a3_joint
      - lwr_a4_joint
      - lwr_a5_joint
      - lwr_a6_joint
