<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>kuka_lwr</name>
  <version>2.0.0</version>
  <description>
    ROS 2 meta-package containing kuka lwr packages.
  </description>
  <maintainer email="carlos.rosales@for.unipi.it">Carlos Rosales</maintainer>

  <license>GPLv2</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- PACKAGES -->

  <!-- Model -->
  <exec_depend>lwr_description</exec_depend>

  <!-- ros2_control-based controllers -->
  <exec_depend>lwr_controllers</exec_depend>

  <!--  Hardware interfaces real/sim -->
  <exec_depend>lwr_hw</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
